# Generated by Django 5.1.6 on 2025-02-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamintojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=20, verbose_name='Gamintojo pavadinimas')),
            ],
            options={
                'verbose_name': 'Gamintojas',
                'verbose_name_plural': 'Gamintojai',
            },
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=20, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=20, verbose_name='Pavarde')),
                ('tel_numeris', models.CharField(max_length=9, verbose_name='Telefono numeris')),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': 'Klientai',
                'ordering': ('pavarde', 'vardas'),
            },
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=50, verbose_name='Pavadinimas')),
                ('kaina', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Kaina')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Iveskite automobilio modelius', max_length=20, verbose_name='Modelio pavadinimas')),
                ('gamintojas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.gamintojas')),
            ],
            options={
                'verbose_name': 'Modelis',
                'verbose_name_plural': 'Modeliai',
            },
        ),
        migrations.CreateModel(
            name='Masina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_numeris', models.CharField(max_length=6, unique=True, verbose_name='Registracijos numeris')),
                ('klientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.klientas')),
                ('modelis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.modelis')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilna_kaina', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pilna kaina')),
                ('date', models.DateField(auto_now_add=True)),
                ('statusas', models.CharField(blank=True, choices=[('p', 'Priimtas'), ('v', 'Vykdomas'), ('a', 'Atliktas')], default='p', help_text='Uzsakymo statusas', max_length=1, verbose_name='Statusas')),
                ('masina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.masina')),
            ],
            options={
                'verbose_name': 'Uzsakymas',
                'verbose_name_plural': 'Uzsakymai',
            },
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.PositiveIntegerField(verbose_name='Kiekis')),
                ('paslaugu_kaina', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Paslaugu kaina')),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.paslauga')),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.uzsakymas')),
            ],
            options={
                'verbose_name': 'Uzsakymo eilute',
                'verbose_name_plural': 'Uzsakymo eilutes',
            },
        ),
    ]
